# Generated by Django 5.0.6 on 2024-06-27 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('strategy_name', models.CharField(choices=[('macd', 'MACD'), ('rsi', 'RSI'), ('sma', 'SMA'), ('ema', 'EMA'), ('bb', 'Bollinger Bands'), ('adx', 'ADX'), ('kc', 'Keltner Channels')], max_length=100)),
                ('para_1', models.IntegerField(max_length=3)),
                ('para_2', models.IntegerField(max_length=3)),
                ('para_3', models.IntegerField(max_length=3)),
                ('para_4', models.IntegerField(max_length=3)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='accounts.userinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
