from accounts.models import TickerSymbol

ticker_data = [
    ("^NSEI", "NIFTY 50"),
    ("^NSEBANK", "NIFTY BANK"),
    ("Aarti Industries", "AARTIIND"),
    ("ABB India Ltd.", "ABB"),
    ("ACC Ltd.", "ACC"),
    ("Adani Enterprises Ltd.", "ADANIENT"),
    ("Adani Ports and Special Economic Zone Ltd.", "ADANIPORTS"),
    ("Adani Power Ltd.", "ADANIPOWER"),
    ("Aditya Birla Capital Ltd.", "ABCAPITAL"),
    ("Aditya Birla Fashion and Retail Ltd.", "ABFRL"),
    ("Alkem Laboratories Ltd.", "ALKEM"),
    ("Ambuja Cements Ltd.", "AMBUJACEM"),
    ("APL Apollo Tubes Ltd.", "APLAPOLLO"),
    ("Apollo Hospitals Enterprise Ltd.", "APOLLOHOSP"),
    ("Apollo Tyres Ltd.", "APOLLOTYRE"),
    ("Archean Chemical Ltd", "ACL"),
    ("Asian Paints Ltd.", "ASIANPAINT"),
    ("Astral Ltd.", "ASTRAL"),
    ("AU Small Finance Bank Ltd.", "AUBANK"),
    #("Aurobindo Pharma Ltd.", "AUROPHARMA"),
    # ("Axis Bank Ltd.", "AXISBANK"),
    ("Bajaj Auto Ltd.", "BAJAJ-AUTO"),
    ("Bajaj Finance Ltd.", "BAJFINANCE"),
    ("Bajaj Finserv Ltd.", "BAJAJFINSV"),
    ("Balkrishna Industries Ltd.", "BALKRISIND"),
    ("Bank of Baroda", "BANKBARODA"),
    ("Bata India Ltd.", "BATAINDIA"),
    ("Berger Paints India Ltd.", "BERGEPAINT"),
    ("Bharat Dynamics Ltd.", "BDL"),
    ("Bharat Electronics Ltd.", "BEL"),
    ("Bharat Forge Ltd.", "BHARATFORG"),
    ("Bharat Heavy Electricals Ltd.", "BHEL"),
    ("Bharat Petroleum Corporation Ltd.", "BPCL"),
    ("Bharti Airtel Ltd.", "BHARTIARTL"),
    ("Biocon Ltd.", "BIOCON"),
    ("Bosch Ltd.", "BOSCHLTD"),
    ("Britannia Industries Ltd.", "BRITANNIA"),
    ("Canara Bank", "CANBK"),
    ("CG Power and Industrial Solutions Ltd.", "CGPOWER"),
    ("Cholamandalam Investment and Finance Company Ltd.", "CHOLAFIN"),
    ("Cipla Ltd.", "CIPLA"),
    ("Coal India Ltd.", "COALINDIA"),
    ("Coforge Ltd.", "COFORGE"),
    ("Colgate Palmolive (India) Ltd.", "COLPAL"),
    ("Container Corporation of India Ltd.", "CONCOR"),
    ("Coromandel International Ltd.", "COROMANDEL"),
    ("Crompton Greaves Consumer Electricals Ltd.", "CROMPTON"),
    ("Cummins India Ltd.", "CUMMINSIND"),
    ("Dabur India Ltd.", "DABUR"),
    ("Dalmia Bharat Ltd.", "DALBHARAT"),
    ("Deepak Nitrite Ltd.", "DEEPAKNTR"),
    ("Delhivery Ltd.", "DELHIVERY"),
    ("Divi's Laboratories Ltd.", "DIVISLAB"),
    ("Dixon Technologies (India) Ltd.", "DIXON"),
    ("DLF Ltd.", "DLF"),
    ("Dr. Reddy's Laboratories Ltd.", "DRREDDY"),
    ("Eicher Motors Ltd.", "EICHERMOT"),
    ("Epigral", "EPIGRAL"),
    ("Escorts Kubota Ltd.", "ESCORTS"),
    ("Fertilisers and Chemicals Travancore Ltd.", "FACT"),
    ("FSN E-Commerce Ventures Ltd.", "NYKAA"),
    ("GAIL (India) Ltd.", "GAIL"),
    ("Gland Pharma Ltd.", "GLAND"),
    ("Godrej Consumer Products Ltd.", "GODREJCP"),
    ("Godrej Properties Ltd.", "GODREJPROP"),
    ("Grasim Industries Ltd.", "GRASIM"),
    ("Gujarat Fluorochemicals Ltd.", "FLUOROCHEM"),
    ("Gujarat Gas Ltd.", "GUJGASLTD"),
    ("Havells India Ltd.", "HAVELLS"),
    ("HCL Technologies Ltd.", "HCLTECH"),
    ("HDFC Asset Management Company Ltd.", "HDFCAMC"),
    #("HDFC Bank Ltd.", "HDFCBANK"),
    ("HDFC Life Insurance Company Ltd.", "HDFCLIFE"),
    ("Hero MotoCorp Ltd.", "HEROMOTOCO"),
    ("Hindalco Industries Ltd.", "HINDALCO"),
    ("Hindustan Aeronautics Ltd.", "HAL"),
    ("Hindustan Petroleum Corporation Ltd.", "HINDPETRO"),
    ("Hindustan Unilever Ltd.", "HINDUNILVR"),
    ("ICICI Bank Ltd.", "ICICIBANK"),
    ("ICICI Lombard General Insurance Company Ltd.", "ICICIGI"),
    ("ICICI Prudential Life Insurance Company Ltd.", "ICICIPRULI"),
    ("IDFC First Bank Ltd.", "IDFCFIRSTB"),
    ("Indian Hotels Co. Ltd.", "INDHOTEL"),
    ("Indian Oil Corporation Ltd.", "IOC"),
    ("Indian Railway Catering And Tourism Corporation Ltd.", "IRCTC"),
    ("Indian Railway Finance Corporation Ltd.", "IRFC"),
    ("Indraprastha Gas Ltd.", "IGL"),
    ("Indus Towers Ltd.", "INDUSTOWER"),
    ("IndusInd Bank Ltd.", "INDUSINDBK"),
    ("Info Edge (India) Ltd.", "NAUKRI"),
    ("Infosys Ltd.", "INFY"),
    ("InterGlobe Aviation Ltd.", "INDIGO"),
    ("Ipca Laboratories Ltd.", "IPCALAB"),
    ("ITC Ltd.", "ITC"),
    ("Jindal Steel & Power Ltd.", "JINDALSTEL"),
    ("JSW Energy Ltd.", "JSWENERGY"),
    ("JSW Steel Ltd.", "JSWSTEEL"),
    ("Jubilant Foodworks Ltd.", "JUBLFOOD"),
    ("Kotak Mahindra Bank Ltd.", "KOTAKBANK"),
    ("KPIT Technologies Ltd.", "KPITTECH"),
    ("L&T Finance Holdings Ltd.", "L&TFH"),
    ("L&T Technology Services Ltd.", "LTTS"),
    ("Larsen & Toubro Ltd.", "LT"),
    ("Latent View Analytics", "LATENTVIEW"),
    ("Laurus Labs Ltd.", "LAURUSLABS"),
    ("LIC Housing Finance Ltd.", "LICHSGFIN"),
    ("Life Insurance Corporation of India", "LICI"),
    ("LTIMindtree Ltd.", "LTIM"),
    ("Lupin Ltd.", "LUPIN"),
    ("Macrotech Developers Ltd.", "LODHA"),
    ("Mahindra & Mahindra Financial Services Ltd.", "M&MFIN"),
    ("Mahindra & Mahindra Ltd.", "M&M"),
    ("Mankind Pharma Ltd.", "MANKIND"),
    ("Marico Ltd.", "MARICO"),
    ("Maruti Suzuki India Ltd.", "MARUTI"),
    ("Max Financial Services Ltd.", "MFSL"),
    ("Max Healthcare Institute Ltd.", "MAXHEALTH"),
    ("Mazagoan Dock Shipbuilders Ltd.", "MAZDOCK"),
    ("Motherson Sumi Wiring India Ltd.", "MSUMI"),
    ("MphasiS Ltd.", "MPHASIS"),
    ("Muthoot Finance Ltd.", "MUTHOOTFIN"),
    ("Navin Fluorine International Ltd.", "NAVINFLUOR"),
    ("Nestle India Ltd.", "NESTLEIND"),
    ("NHPC Ltd.", "NHPC"),
    ("NMDC Ltd.", "NMDC"),
    ("NTPC Ltd.", "NTPC"),
    ("Oberoi Realty Ltd.", "OBEROIRLTY"),
    ("Oil & Natural Gas Corporation Ltd.", "ONGC"),
    ("Oil India Ltd.", "OIL"),
    ("Page Industries Ltd.", "PAGEIND"),
    ("Patanjali Foods Ltd.", "PATANJALI"),
    ("PB Fintech Ltd.", "POLICYBZR"),
    ("Persistent Systems Ltd.", "PERSISTENT"),
    ("Petronet LNG Ltd.", "PETRONET"),
    ("PI Industries Ltd.", "PIIND"),
    ("Pidilite Industries Ltd.", "PIDILITIND"),
    ("Piramal Enterprises Ltd.", "PEL"),
    ("Polycab India Ltd.", "POLYCAB"),
    ("Power Finance Corporation Ltd.", "PFC"),
    ("Power Grid Corporation of India Ltd.", "POWERGRID"),
    ("Prestige Estates Projects Ltd.", "PRESTIGE"),
    ("Procter & Gamble Hygiene & Health Care Ltd.", "PGHH"),
    ("Punjab National Bank", "PNB"),
    ("REC Ltd.", "RECLTD"),
    ("Reliance Industries Ltd.", "RELIANCE"),
    ("Samvardhana Motherson International Ltd.", "MOTHERSON"),
    ("SBI Cards and Payment Services Ltd.", "SBICARD"),
    ("SBI Life Insurance Company Ltd.", "SBILIFE"),
    ("Shree Cement Ltd.", "SHREECEM"),
    ("Shriram Finance Ltd.", "SHRIRAMFIN"),
    ("Siemens Ltd.", "SIEMENS"),
    ("Sona BLW Precision Forgings Ltd.", "SONACOMS"),
    ("SRF Ltd.", "SRF"),
    ("State Bank of India", "SBIN"),
    ("Steel Authority of India Ltd.", "SAIL"),
    ("Sun Pharmaceutical Industries Ltd.", "SUNPHARMA"),
    ("Sun TV Network Ltd.", "SUNTV"),
    ("Syngene International Ltd.", "SYNGENE"),
    ("Tata Chemicals Ltd.", "TATACHEM"),
    ("Tata Communications Ltd.", "TATACOMM"),
    ("Tata Consultancy Services Ltd.", "TCS"),
    ("Tata Consumer Products Ltd.", "TATACONSUM"),
    ("Tata Elxsi Ltd.", "TATAELXSI"),
    ("Tata Motors Ltd DVR", "TATAMTRDVR"),
    ("Tata Motors Ltd.", "TATAMOTORS"),
    ("Tata Power Co. Ltd.", "TATAPOWER"),
    ("Tata Steel Ltd.", "TATASTEEL"),
    ("Tech Mahindra Ltd.", "TECHM"),
    ("The Ramco Cements Ltd.", "RAMCOCEM"),
    ("Titan Company Ltd.", "TITAN"),
    ("Torrent Pharmaceuticals Ltd.", "TORNTPHARM"),
    ("Torrent Power Ltd.", "TORNTPOWER"),
    ("Trent Ltd.", "TRENT"),
    ("Tube Investments of India Ltd.", "TIINDIA"),
    ("TVS Motor Company Ltd.", "TVSMOTOR"),
    ("UltraTech Cement Ltd.", "ULTRACEMCO"),
    ("Union Bank of India", "UNIONBANK"),
    ("United Breweries Ltd.", "UBL"),
    ("United Spirits Ltd.", "MCDOWELL-N"),
    ("UPL Ltd.", "UPL"),
    ("Varun Beverages Ltd.", "VBL"),
    ("Vedanta Ltd.", "VEDL"),
    ("Voltas Ltd.", "VOLTAS"),
    ("Wipro Ltd.", "WIPRO"),
    ("Yes Bank Ltd.", "YESBANK"),
    #("Zydus Lifesciences Ltd.", "ZYDUSLIFE"),
]


def create_ticker_symbols():
    for ticker_name, symbol in ticker_data:
        TickerSymbol.objects.create(ticker=symbol, symbol_name=ticker_name)